# Einführung in NumPy

In dieser Lektion stellen wir **NumPy** vor – eine leistungsstarke Bibliothek für numerische Berechnungen in Python. Wir werden folgende Themen behandeln:

- Was ist NumPy und warum sollte man es verwenden?
- Installation und Import von NumPy
- Erstellen von NumPy-Arrays und Erkundung ihrer Attribute
- Array-Operationen (Indexierung, Slicing, mathematische Operationen, Broadcasting, Aggregatfunktionen)
- Matrixoperationen (Erstellung, Multiplikation, Transponieren, Umformen)
- Praktische Übungen zur Anwendung dieser Konzepte

## Was ist NumPy und warum sollte man es verwenden?

- **NumPy** steht für *Numerical Python* und ist eine der zentralen Bibliotheken für numerische Berechnungen.
- Es bietet Unterstützung für große, mehrdimensionale Arrays und Matrizen.
- Viele eingebaute mathematische Funktionen ermöglichen eine effiziente Verarbeitung dieser Arrays.

### Vorteile:

- **Leistung:** Array-Operationen sind in C implementiert und daher deutlich schneller als Python-Schleifen.
- **Speichereffizienz:** Arrays sind dicht gepackt und benötigen weniger Speicher als Python-Listen.
- **Funktionalität:** Es gibt viele vektorisierte Operationen und Funktionen für lineare Algebra, Statistik und mehr.

## Installation und Import von NumPy

Falls NumPy noch nicht installiert ist, führe folgenden Befehl im Terminal oder in einer Notebook-Zelle aus:

```python
!pip install numpy
```

Importiere NumPy in deinem Python-Code mit:

```python
import numpy as np
```

In [3]:
# Importiere NumPy
import numpy as np

# Erstelle ein grundlegendes NumPy-Array aus einer Python-Liste
array_from_list = np.array([1, 2, 3, 4, 5])
print('Array aus Liste:', array_from_list)

Array aus Liste: [1 2 3 4 5]


## NumPy-Arrays vs. Python-Listen

- **Homogenität:** NumPy-Arrays sind homogen (alle Elemente haben denselben Typ), während Python-Listen gemischte Typen enthalten können.
- **Leistung:** NumPy-Arrays unterstützen vektorisierte Operationen und sind für numerische Aufgaben viel schneller.
- **Speichereffizienz:** Arrays benötigen weniger Speicher als Listen.
- **Funktionalität:** Viele eingebaute mathematische Operationen sind direkt auf NumPy-Arrays anwendbar.

In [4]:
# Vergleich von Python-Listen und NumPy-Arrays
python_list = [1, 2, 3, 4, 5]
numpy_array = np.array([1, 2, 3, 4, 5])

# Multipliziert man eine Python-Liste mit 2, wird die Liste repliziert
print('Python-Liste multipliziert mit 2:', python_list * 2)

# Bei einem NumPy-Array wird jedes Element mit 2 multipliziert
print('NumPy-Array multipliziert mit 2:', numpy_array * 2)

Python-Liste multipliziert mit 2: [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
NumPy-Array multipliziert mit 2: [ 2  4  6  8 10]


## Erstellen von NumPy-Arrays

Es gibt verschiedene Möglichkeiten, Arrays in NumPy zu erstellen:

### 1. Verwendung von `np.array`

Konvertiere eine Python-Liste in ein NumPy-Array.

In [5]:
data = [10, 20, 30, 40, 50]
arr = np.array(data)
print('NumPy-Array:', arr)

NumPy-Array: [10 20 30 40 50]


### 2. Verwendung von `np.zeros` und `np.ones`

- `np.zeros(shape)` erstellt ein Array, das mit Nullen gefüllt ist.
- `np.ones(shape)` erstellt ein Array, das mit Einsen gefüllt ist.

In [6]:
# Array mit Nullen: 3 Zeilen x 4 Spalten
nullen_array = np.zeros((3, 4))
print('Nullen-Array:\n', nullen_array)

# Array mit Einsen: 2 Zeilen x 5 Spalten
einsen_array = np.ones((2, 5))
print('Einsen-Array:\n', einsen_array)

Nullen-Array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Einsen-Array:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


### 3. Verwendung von `np.arange` und `np.linspace`

- `np.arange(start, stop, step)` erstellt ein Array mit gleichmäßig verteilten Werten.
- `np.linspace(start, stop, num)` erstellt ein Array mit einer festgelegten Anzahl gleichmäßig verteilter Werte.

In [7]:
# Mit np.arange: Werte von 0 bis 8 (Schrittweite 2)
arange_array = np.arange(0, 10, 2)
print('np.arange:', arange_array)

# Mit np.linspace: 5 Werte gleichmäßig verteilt zwischen 0 und 1
linspace_array = np.linspace(0, 1, 5)
print('np.linspace:', linspace_array)

np.arange: [0 2 4 6 8]
np.linspace: [0.   0.25 0.5  0.75 1.  ]


## Array-Attribute

Jedes NumPy-Array besitzt mehrere nützliche Attribute:

- **`shape`**: Die Dimensionen des Arrays (Zeilen, Spalten etc.)
- **`dtype`**: Der Datentyp der Elemente
- **`size`**: Gesamtanzahl der Elemente im Array
- **`ndim`**: Anzahl der Dimensionen (Achsen) des Arrays

In [8]:
beispiel_array = np.array([[1, 2, 3], [4, 5, 6]])
print('Array:')
print(beispiel_array)

print('Shape:', beispiel_array.shape)
print('Datentyp:', beispiel_array.dtype)
print('Anzahl der Elemente:', beispiel_array.size)
print('Anzahl der Dimensionen:', beispiel_array.ndim)

Array:
[[1 2 3]
 [4 5 6]]
Form: (2, 3)
Datentyp: int64
Anzahl der Elemente: 6
Anzahl der Dimensionen: 2


## Array-Operationen

### Indexierung und Slicing

Auf Elemente eines NumPy-Arrays kann man ähnlich wie bei Python-Listen zugreifen:

- **Indexierung:** Verwende eckige Klammern `[]` mit dem Index (beginnend bei 0), um ein einzelnes Element abzurufen.
- **Slicing:** Verwende den Doppelpunkt `:`, um einen Teil des Arrays auszuwählen.

In [9]:
beispiel_array = np.array([10, 20, 30, 40, 50])

# Indexierung: Hole das dritte Element (Index 2)
print('Drittes Element:', beispiel_array[2])

# Slicing: Hole Elemente von Index 1 bis 3 (Index 4 wird ausgeschlossen)
print('Slice von Index 1 bis 4:', beispiel_array[1:4])

Drittes Element: 30
Slice von Index 1 bis 4: [20 30 40]


### Mathematische Operationen (Elementweise)

NumPy ermöglicht arithmetische Operationen auf Arrays elementweise.

In [10]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print('Addition:', a + b)
print('Subtraktion:', a - b)
print('Multiplikation:', a * b)
print('Division:', a / b)

Addition: [5 7 9]
Subtraktion: [-3 -3 -3]
Multiplikation: [ 4 10 18]
Division: [0.25 0.4  0.5 ]


### Broadcasting

Broadcasting ermöglicht es NumPy, Operationen auf Arrays unterschiedlicher Formen durchzuführen, indem das kleinere Array entlang der fehlenden Dimensionen erweitert wird. Zum Beispiel das Addieren eines Vektors zu jeder Zeile einer Matrix.

In [11]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
vektor = np.array([1, 0, 1])

# Broadcasting: Addiere den Vektor zu jeder Zeile der Matrix
ergebnis = matrix + vektor
print('Matrix:\n', matrix)
print('Vektor:', vektor)
print('Ergebnis der Broadcasting-Addition:\n', ergebnis)

Matrix:
 [[1 2 3]
 [4 5 6]]
Vektor: [1 0 1]
Ergebnis der Broadcasting-Addition:
 [[2 2 4]
 [5 5 7]]


### Aggregatfunktionen

NumPy bietet Funktionen, um Werte in einem Array zu aggregieren:

- **`np.sum()`**: Summe aller Elemente
- **`np.mean()`**: Durchschnitt (Mittelwert) der Elemente
- **`np.std()`**: Standardabweichung
- **`np.min()`**: Minimaler Wert
- **`np.max()`**: Maximaler Wert

In [12]:
data = np.array([1, 2, 3, 4, 5])

print('Summe:', np.sum(data))
print('Mittelwert:', np.mean(data))
print('Standardabweichung:', np.std(data))
print('Minimaler Wert:', np.min(data))
print('Maximaler Wert:', np.max(data))

Summe: 15
Mittelwert: 3.0
Standardabweichung: 1.4142135623730951
Minimaler Wert: 1
Maximaler Wert: 5


## Matrix-Operationen

### Erstellen von Matrizen

NumPy bietet Funktionen, um spezielle Matrizen zu erstellen:

- **`np.eye(n)`**: Erstellt eine *n x n* Einheitsmatrix
- **`np.random.rand(m, n)`**: Erstellt eine *m x n* Matrix mit zufälligen Werten zwischen 0 und 1

In [13]:
# Einheitsmatrix der Größe 4x4
einheitsmatrix = np.eye(4)
print('Einheitsmatrix:\n', einheitsmatrix)

# Zufällige 3x3 Matrix
random_matrix = np.random.rand(3, 3)
print('Zufalls-Matrix:\n', random_matrix)

Einheitsmatrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Zufalls-Matrix:
 [[0.21869761 0.15369436 0.40683467]
 [0.82235324 0.25828387 0.32539224]
 [0.92198685 0.43789583 0.27684496]]


### Matrixmultiplikation

Führe Matrixmultiplikation entweder mit `np.dot` oder dem `@`-Operator durch.

In [14]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Mit np.dot
produkt_dot = np.dot(A, B)
print('Matrixmultiplikation mit np.dot:\n', produkt_dot)

# Mit dem @-Operator
produkt_operator = A @ B
print('Matrixmultiplikation mit @-Operator:\n', produkt_operator)

Matrixmultiplikation mit np.dot:
 [[19 22]
 [43 50]]
Matrixmultiplikation mit @-Operator:
 [[19 22]
 [43 50]]


### Transponieren und Umformen

- **Transponieren:** Vertausche Zeilen und Spalten mit `.T`.
- **Umformen:** Ändere die Form eines Arrays mit `np.reshape` (die Gesamtzahl der Elemente muss gleich bleiben).

In [15]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])

# Transponiere die Matrix
transponierte_matrix = matrix.T
print('Originale Matrix:\n', matrix)
print('Transponierte Matrix:\n', transponierte_matrix)

# Forme die Matrix um zu einem 3x2 Array
umgeformte_matrix = np.reshape(matrix, (3, 2))
print('Umgeformte Matrix (3x2):\n', umgeformte_matrix)

Originale Matrix:
 [[1 2 3]
 [4 5 6]]
Transponierte Matrix:
 [[1 4]
 [2 5]
 [3 6]]
Umgeformte Matrix (3x2):
 [[1 2]
 [3 4]
 [5 6]]


## Praktische Übungen

### Übung 1: Erstelle ein Array und führe Operationen aus

1. Erstelle ein 2D NumPy-Array der Form **(4, 5)** mit zufälligen Ganzzahlen zwischen 0 und 50.
2. Berechne die **Gesamtsumme** aller Elemente im Array.
3. Ermittle den **Mittelwert** jeder Spalte.

In [16]:
# Lösung zu Übung 1
array_uebung1 = np.random.randint(0, 51, (4, 5))
print('Übungs-Array:\n', array_uebung1)

gesamt_summe = np.sum(array_uebung1)
print('Gesamtsumme der Elemente:', gesamt_summe)

spalten_mittelwert = np.mean(array_uebung1, axis=0)  # axis=0 berechnet den Mittelwert spaltenweise
print('Mittelwert jeder Spalte:', spalten_mittelwert)

Übungs-Array:
 [[44 21 32 43 20]
 [31 40 36 49 40]
 [41 16 27 33 37]
 [20 38 19 39 22]]
Gesamtsumme der Elemente: 648
Mittelwert jeder Spalte: [34.   28.75 28.5  41.   29.75]


### Übung 2: Berechne Statistiken für einen Datensatz mit NumPy

Gegeben sei der folgende Datensatz von Prüfungsergebnissen. Berechne:

- Den **Gesamtdurchschnitt** der Noten
- Die **Standardabweichung** der Noten
- Den **höchsten** und **niedrigsten** Wert

Datensatz: `[88, 92, 79, 93, 85, 78, 91, 87, 95, 89]`

In [17]:
# Lösung zu Übung 2
noten = np.array([88, 92, 79, 93, 85, 78, 91, 87, 95, 89])

durchschnitt = np.mean(noten)
standardabweichung = np.std(noten)
min_wert = np.min(noten)
max_wert = np.max(noten)

print('Durchschnitt:', durchschnitt)
print('Standardabweichung:', standardabweichung)
print('Niedrigster Wert:', min_wert)
print('Höchster Wert:', max_wert)

Durchschnitt: 87.7
Standardabweichung: 5.386093203798093
Niedrigster Wert: 78
Höchster Wert: 95


### Übung 3: Einfache numerische Berechnung

Stell dir vor, du hast ein Array, das die zurückgelegten Entfernungen (in Kilometern) verschiedener Fahrzeuge darstellt.

1. Erstelle ein Array mit den folgenden Entfernungen: `[15, 30, 45, 60, 75]`.
2. Wandle diese Entfernungen in **Meilen** um (Umrechnungsfaktor: 1 km = 0.621371 Meilen).
3. Berechne die **Gesamtentfernung** in Meilen.

In [18]:
# Lösung zu Übung 3
entfernungen_km = np.array([15, 30, 45, 60, 75])
umrechnungsfaktor = 0.621371

# Wandle Entfernungen in Meilen um
entfernungen_meilen = entfernungen_km * umrechnungsfaktor
print('Entfernungen in Meilen:', entfernungen_meilen)

# Berechne die Gesamtentfernung in Meilen
gesamt_entfernung_meilen = np.sum(entfernungen_meilen)
print('Gesamtentfernung in Meilen:', gesamt_entfernung_meilen)

Entfernungen in Meilen: [ 9.320565 18.64113  27.961695 37.28226  46.602825]
Gesamtentfernung in Meilen: 139.808475


## Zusammenfassung

In diesem Notebook haben wir gelernt:

- Die Bedeutung und Vorteile von NumPy
- Wie man NumPy installiert und importiert
- Verschiedene Möglichkeiten, Arrays zu erstellen und deren Eigenschaften zu inspizieren
- Array-Operationen wie Indexierung, Slicing, elementweise arithmetische Operationen und Broadcasting
- Matrixoperationen wie Multiplikation, Transponieren und Umformen
- Praktische Übungen zur Anwendung dieser Konzepte

Diese Grundlagen sind hilfreich, wenn wir in der nächsten Lektion fortgeschrittene Datenmanipulationsbibliotheken wie **Pandas** erkunden.

### Nächste Schritte

In der nächsten Lektion werden wir uns mit **Pandas** beschäftigen – einer leistungsstarken Bibliothek zur Datenmanipulation und -analyse in Python. Bleib dran!

## Weiterführende Ressourcen zu NumPy

NumPy bietet eine Vielzahl von Funktionen für numerische Berechnungen, die weit über das hinausgehen, was wir in dieser Einführung behandelt haben. 
Es ist wichtig, regelmäßig die **offizielle Dokumentation** und verschiedene **Tutorials** zu lesen, um NumPy effektiv zu nutzen.

### Offizielle Dokumentation und Einsteigerleitfäden:
- [NumPy Quickstart Tutorial](https://numpy.org/doc/stable/user/quickstart.html)
- [NumPy Leitfaden für absolute Anfänger](https://numpy.org/doc/stable/user/absolute_beginners.html)

### Illustrierte NumPy-Tutorials:
- [NumPy Illustrated: The Visual Guide to NumPy](https://medium.com/better-programming/numpy-illustrated-the-visual-guide-to-numpy-3b1d4976de1d)
- [A Visual Intro to NumPy and Data Representation](https://jalammar.github.io/visual-numpy/)

Diese Ressourcen enthalten detaillierte Erklärungen und **grafische Darstellungen**, die helfen, NumPy besser zu verstehen. Sie eignen sich hervorragend für das eigenständige Lernen und zur Vertiefung der Kenntnisse nach diesem Kurs.